"""add message sequence and score

Revision ID: 4c3f271b3eab
Revises: cc5c1181a9e4
Create Date: 2026-09-29 12:46:22.612783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3f271b3eab'
down_revision: Union[str, Sequence[str], None] = 'cc5c1181a9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sequence', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('q', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_messages_session_id_sequence', 'messages', ['session_id', 'sequence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_messages_session_id_sequence', 'messages', type_='unique')
    op.drop_column('messages', 'q')
    op.drop_column('messages', 'sequence')
    # ### end Alembic commands ###
